SET IDENTITY_INSERT GoodModelBaseType ON;
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (1,'Smartphone','Condor Electronics',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (2,'Smartphone','Proton',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (3,'Smartphone','Symphony',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (4,'Smartphone','Walton',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (5,'Smartphone','Gradiente',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (6,'Smartphone','Multilaser',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (7,'Smartphone','Positivo',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (8,'Smartphone','Tectoy',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (9,'Smartphone','Coolpad',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (10,'Smartphone','Cubot',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (11,'Smartphone','Gfive',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (12,'Smartphone','Haier',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (13,'Smartphone','Hisense',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (14,'Smartphone','Honor',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (15,'Smartphone','Huawei',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (16,'Smartphone','Infinix',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (17,'Smartphone','Itel Mobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (18,'Smartphone','iQOO',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (19,'Smartphone','LeEco',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (20,'Smartphone','Meitu',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (21,'Smartphone','Meizu',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (22,'Smartphone','Ningbo Bird',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (23,'Smartphone','Nubia',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (24,'Smartphone','OnePlus',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (25,'Smartphone','Oppo',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (26,'Smartphone','Poco',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (27,'Smartphone','Realme',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (28,'Smartphone','Redmagic',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (29,'Smartphone','Redmi',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (30,'Smartphone','Smartisan',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (31,'Smartphone','TCL Corporation',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (32,'Smartphone','Technology Happy Life',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (33,'Smartphone','Tecno Mobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (34,'Smartphone','Umidigi',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (35,'Smartphone','Vivo',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (36,'Smartphone','Wasam',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (37,'Smartphone','Unihertz',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (38,'Smartphone','Xiaomi',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (39,'Smartphone','ZTE',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (40,'Smartphone','Jablotron',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (41,'Smartphone','Verzo',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (42,'Smartphone','SICO Technology',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (43,'Smartphone','Jolla',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (44,'Smartphone','Nokia Corporation',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (45,'Smartphone','HMD Global',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (46,'Smartphone','Bittium',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (47,'Smartphone','Archos',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (48,'Smartphone','Alcatel Mobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (49,'Smartphone','Crosscall',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (50,'Smartphone','Groupe Bull',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (51,'Smartphone','Kapsys',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (52,'Smartphone','Logicom',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (53,'Smartphone','MobiWire',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (54,'Smartphone','Wiko',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (55,'Smartphone','Gigaset',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (56,'Smartphone','Medion',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (57,'Smartphone','SHIFT',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (58,'Smartphone','TechniSat',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (59,'Smartphone','Tiptel',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (60,'Smartphone','MLS',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (61,'Smartphone','X-tigi Mobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (62,'Smartphone','Lenovo',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (63,'Smartphone','Intex Technologies',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (64,'Smartphone','Karbonn Mobiles',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (65,'Smartphone','Lava International',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (66,'Smartphone','Jio',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (67,'Smartphone','LYF',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (68,'Smartphone','Micromax Informatics',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (69,'Smartphone','Xolo',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (70,'Smartphone','GLX',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (71,'Smartphone','Daria',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (72,'Smartphone','Gplus',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (73,'Smartphone','Advan',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (74,'Smartphone','Evercoss',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (75,'Smartphone','SPC',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (76,'Smartphone','Brondi',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (77,'Smartphone','Q.Bell[4]',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (78,'Smartphone','New Generation Mobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (79,'Smartphone','Olivetti',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (80,'Smartphone','Akai',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (81,'Smartphone','Fujitsu',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (82,'Smartphone','Casio',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (83,'Smartphone','Hitachi',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (84,'Smartphone','JRC',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (85,'Smartphone','Kyocera',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (86,'Smartphone','Mitsubishi Electric',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (87,'Smartphone','NEC',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (88,'Smartphone','Panasonic',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (89,'Smartphone','Sharp',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (90,'Smartphone','Sony',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (91,'Smartphone','Toshiba',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (92,'Smartphone','Just5',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (93,'Smartphone','Kyoto Electronics',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (94,'Smartphone','Lanix',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (95,'Smartphone','Zonda',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (96,'Smartphone','MYFON',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (97,'Smartphone','VC Group',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (98,'Smartphone','Fairphone',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (99,'Smartphone','John''s Phone',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (100,'Smartphone','Philips',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (101,'Smartphone','Arirang',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (102,'Smartphone','QMobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (103,'Smartphone','Cherry Mobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (104,'Smartphone','Cloudfone',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (105,'Smartphone','Firefly Mobile (PH)',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (106,'Smartphone','Starmobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (107,'Smartphone','SKK Mobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (108,'Smartphone','MyPhone',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (109,'Smartphone','Torque Mobile',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (110,'Smartphone','O+ USA',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (111,'Smartphone','Kruger&Matz',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (112,'Smartphone','Manta Multimedia',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (113,'Smartphone','myPhone (Poland)',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (114,'Smartphone','Allview',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (115,'Smartphone','Evolio',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (116,'Smartphone','E-Boda',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (117,'Smartphone','Myria',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (118,'Smartphone','Utok',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (119,'Smartphone','Beeline',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (120,'Smartphone','Explay',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (121,'Smartphone','Gresso',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (122,'Smartphone','Highscreen',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (123,'Smartphone','Megafon',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (124,'Smartphone','MTS',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (125,'Smartphone','RoverPC',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (126,'Smartphone','teXet',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (127,'Smartphone','Sitronics',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (128,'Smartphone','Yotaphone',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (129,'Smartphone','Cell C',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (130,'Smartphone','MTN',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (131,'Smartphone','Mobicel',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (132,'Smartphone','Telkom',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (133,'Smartphone','Vodacom',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (134,'Smartphone','Samsung',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (135,'Smartphone','Doro',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (136,'Smartphone','Acer',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (137,'Smartphone','Asus',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (138,'Smartphone','BenQ',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (139,'Smartphone','DBTel',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (140,'Smartphone','Foxconn',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (141,'Smartphone','HTC',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (142,'Smartphone','AIS',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (143,'Smartphone','DTAC',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (144,'Smartphone','TRUE',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (145,'Smartphone','Wellcom',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (146,'Smartphone','EvertekTunisie',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (147,'Smartphone','Vestel',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (148,'Smartphone','Thuraya',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (149,'Smartphone','Bullitt Group',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (150,'Smartphone','Nothing',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (151,'Smartphone','Apple',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (152,'Smartphone','BLU Products',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (153,'Smartphone','Caterpillar',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (154,'Smartphone','Garmin',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (155,'Smartphone','Google Pixel',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (156,'Smartphone','HP',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (157,'Smartphone','iDroid USA',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (158,'Smartphone','InFocus',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (159,'Smartphone','InfoSonics[7]',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (160,'Smartphone','Microsoft',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (161,'Smartphone','Motorola Mobility',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (162,'Smartphone','Purism, SPC',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (163,'Smartphone','BPhone',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (164,'Smartphone','Masstel',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (165,'Smartphone','Masscom',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate) values (166,'Smartphone','Vsmart',GETDATE(),GETDATE());
insert into GoodModelBaseType (Id, Description, Manufacturer, CreatedDate, UpdatedDate)values (167, 'Smartphone', 'GTel', GETDATE(), GETDATE());
SET IDENTITY_INSERT GoodModelBaseType OFF;