SET IDENTITY_INSERT GoodsTypes ON;

insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (1,134,'S20','S20 Phone',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (2,134,'S21','S21 Phone',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (3,134,'S22','S22 Phone',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (4,134,'S23','S23 Phone',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (5,134,'S24','S24 Phone',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (6,134,'S25','S25 Phone',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (7,151,'iPhone','iPhone',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (8,151,'iPhone 3G','iPhone 3G',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (9,151,'iPhone 3GS','iPhone 3GS',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (10,151,'iPhone 4','iPhone 4',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (11,151,'iPhone 4s','iPhone 4s',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (12,151,'iPhone 5','iPhone 5',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (13,151,'iPhone 5c','iPhone 5c',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (14,151,'iPhone 5s','iPhone 5s',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (15,151,'iPhone 6/6 Plus','iPhone 6/6 Plus',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (16,151,'iPhone 6','iPhone 6',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (17,151,'iPhone 6s Plus','iPhone 6s Plus',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (18,151,'iPhone SE (1st)','iPhone SE (1st)',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (19,151,'IPhone 7','IPhone 7',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (20,151,'IPhone 7 Plus','IPhone 7 Plus',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (21,151,'iPhone 8','iPhone 8',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (22,151,'Iphone 8 Plus','Iphone 8 Plus',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (23,151,'iPhone X','iPhone X',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (24,151,'iPhone XS ','iPhone XS ',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (25,151,'iPhone XSMax','iPhone XSMax',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (26,151,'iPhone XR','iPhone XR',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (27,151,'iPhone 11','iPhone 11',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (28,151,'iPhone 11 Pro','iPhone 11 Pro',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (29,151,'IPhone 11 Pro Max','IPhone 11 Pro Max',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (30,151,'iPhone SE (2nd)','iPhone SE (2nd)',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (31,151,'iPhone 12','iPhone 12',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (32,151,'IPhone 12 mini','IPhone 12 mini',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (33,151,'iPhone 12 Pro','iPhone 12 Pro',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (34,151,'IPhone 12 Pro Max','IPhone 12 Pro Max',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (35,151,'iPhone 13','iPhone 13',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (36,151,'IPhone 13 mini','IPhone 13 mini',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (37,151,'iPhone 13 Pro','iPhone 13 Pro',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (38,151,'IPhone 13 Pro Max','IPhone 13 Pro Max',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (39,151,'iPhone SE (3rd)','iPhone SE (3rd)',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (40,151,'iPhone 14','iPhone 14',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (41,151,'iPhone14 Plus','iPhone14 Plus',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (42,151,'iPhone 14 Pro','iPhone 14 Pro',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (43,151,'iPhone14 Pro Max','iPhone14 Pro Max',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (44,151,'iPhone 15','iPhone 15',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (45,151,'iPhone15 Plus','iPhone15 Plus',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (46,151,'iPhone 15 Pro','iPhone 15 Pro',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (47,151,'IPhone 15 Pro Max','IPhone 15 Pro Max',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (48,151,'iPhone 16','iPhone 16',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (49,151,'IPhone 16 Plus','IPhone 16 Plus',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (50,151,'iPhone 16 Pro','iPhone 16 Pro',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (51,151,'IPhone 16 Pro Max','IPhone 16 Pro Max',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (52,151,'iPhone 16e','iPhone 16e',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (53,151,'iPhone 17','iPhone 17',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (54,151,'iPhone Air','iPhone Air',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (55,151,'iPhone 17 Pro','iPhone 17 Pro',1,GETDATE(),GETDATE());
insert into GoodsTypes (Id, GoodBaseId, Name, Description,InventoryKey, CreatedDate, UpdatedDate) values (56,151,'IPhone 17 Pro Max','IPhone 17 Pro Max',1,GETDATE(),GETDATE());


SET IDENTITY_INSERT GoodsTypes OFF;