// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksAPI.DataBaseContext;

#nullable disable

namespace TasksAPI.Migrations
{
    [DbContext(typeof(DatabaseConnectContext))]
    [Migration("20260216192514_ManyToMany")]
    partial class ManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocationTypesInstancesTasksEntitiesProcurements", b =>
                {
                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("LocationTypesInstancesId")
                        .HasColumnType("int");

                    b.HasKey("Location", "LocationTypesInstancesId");

                    b.HasIndex("LocationTypesInstancesId");

                    b.ToTable("LocationTypesInstancesTasksEntitiesProcurements");
                });

            modelBuilder.Entity("TasksAPI.Entities.Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TasksAPI.Entities.AccountsGoodsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountsGoodsEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.ToTable("CashRegisterEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntitySessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedClerk")
                        .HasColumnType("int");

                    b.Property<int>("CashRegisterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CloseHour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<DateTime>("OpenHour")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedClerk");

                    b.HasIndex("CashRegisterID");

                    b.ToTable("CashRegisterEntitySessions");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodModelBaseTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GoodModelBaseType");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodBaseId")
                        .HasColumnType("int");

                    b.Property<int>("InventoryKey")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoodBaseId");

                    b.ToTable("GoodsTypes");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypesInstances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodModelId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("serialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoodModelId");

                    b.HasIndex("LocationId");

                    b.ToTable("GoodsTypesInstances");
                });

            modelBuilder.Entity("TasksAPI.Entities.ItemMovementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromLocation")
                        .HasColumnType("int");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<int>("ToLocation")
                        .HasColumnType("int");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("goodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ItemMovementEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationType")
                        .IsUnique();

                    b.ToTable("LocationEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7317),
                            Description = "Warehouse",
                            LocationType = 1,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7318)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7543),
                            Description = "STORE",
                            LocationType = 2,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7543)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7544),
                            Description = "CLIENT",
                            LocationType = 3,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7544)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7545),
                            Description = "SUPPLIER",
                            LocationType = 4,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7545)
                        });
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypesInstances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeID");

                    b.ToTable("LocationTypesInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Iasi",
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7718),
                            Description = "MAIN Warehouse",
                            LocationTypeID = 1,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7718)
                        },
                        new
                        {
                            Id = 2,
                            Address = "Iasi",
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7936),
                            Description = "Iasi Mall",
                            LocationTypeID = 2,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7937)
                        },
                        new
                        {
                            Id = 3,
                            Address = "Suceava",
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7938),
                            Description = "Suceava Mall",
                            LocationTypeID = 2,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7938)
                        },
                        new
                        {
                            Id = 4,
                            Address = "Client",
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7939),
                            Description = "Goods Assigned to clients",
                            LocationTypeID = 3,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7939)
                        },
                        new
                        {
                            Id = 5,
                            Address = "Iasi",
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7940),
                            Description = "Returned Items",
                            LocationTypeID = 1,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7940)
                        },
                        new
                        {
                            Id = 6,
                            Address = "Iasi",
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7941),
                            Description = "Item Supplier",
                            LocationTypeID = 4,
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(7941)
                        });
                });

            modelBuilder.Entity("TasksAPI.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("RefreshTokenEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.ReportsEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportMode")
                        .HasColumnType("int");

                    b.Property<int>("ReportStatus")
                        .HasColumnType("int");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReportsEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.ReportsEntitiesResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<string>("ReportResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportsEntitiesResults");
                });

            modelBuilder.Entity("TasksAPI.Entities.StoreCartsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Remaining")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("clerktId")
                        .HasColumnType("int");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<int>("storeLocation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreCartsEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.StoreCartsEntityDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("StoreCartsEntityDetails");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("TasksEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntitiesProcurements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoodTypeID");

                    b.HasIndex("TaskID");

                    b.ToTable("TasksEntitiesProcurements");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntitiesTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromLocation")
                        .HasColumnType("int");

                    b.Property<string>("FromLocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodID")
                        .HasColumnType("int");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("int");

                    b.Property<int>("ToLocation")
                        .HasColumnType("int");

                    b.Property<string>("ToLocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("serialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoodID");

                    b.HasIndex("TaskID");

                    b.HasIndex("ToLocation");

                    b.ToTable("TasksEntitiesTransfer");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(4198),
                            Description = "Client",
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(4320),
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(4623),
                            Description = "Clerk",
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(4623),
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(4624),
                            Description = "Supervisor",
                            UpdatedDate = new DateTime(2026, 2, 16, 19, 25, 14, 32, DateTimeKind.Utc).AddTicks(4624),
                            UserTypeId = 4
                        });
                });

            modelBuilder.Entity("TasksAPI.Entities.v_GoodsTypes", b =>
                {
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("GoodBaseId")
                        .HasColumnType("int")
                        .HasColumnName("GoodBaseId");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("InventoryKey")
                        .HasColumnType("int")
                        .HasColumnName("InventoryKey");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.ToTable((string)null);

                    b.ToView("v_GoodsTypes", (string)null);
                });

            modelBuilder.Entity("TasksAPI.Entities.v_GoodsTypesInstances", b =>
                {
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodBaseId")
                        .HasColumnType("int")
                        .HasColumnName("GoodBaseId");

                    b.Property<int>("GoodModelId")
                        .HasColumnType("int")
                        .HasColumnName("GoodModelId");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationId");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LocationName");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Manufacturer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SerialNumber");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.ToTable((string)null);

                    b.ToView("v_GoodsTypesInstances", (string)null);
                });

            modelBuilder.Entity("LocationTypesInstancesTasksEntitiesProcurements", b =>
                {
                    b.HasOne("TasksAPI.Entities.TasksEntitiesProcurements", null)
                        .WithMany()
                        .HasForeignKey("Location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.LocationTypesInstances", null)
                        .WithMany()
                        .HasForeignKey("LocationTypesInstancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TasksAPI.Entities.Accounts", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserTypes", "UserTypes")
                        .WithMany("Accounts")
                        .HasForeignKey("UserTypeId")
                        .HasPrincipalKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTypes");
                });

            modelBuilder.Entity("TasksAPI.Entities.AccountsGoodsEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.Accounts", "Accounts")
                        .WithMany("AccountsGoodsEntity")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.LocationTypesInstances", "LocationTypesInstances")
                        .WithMany("CashRegisterEntity")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationTypesInstances");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntitySessions", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserEntity", "User")
                        .WithMany("CashRegisterEntitySessions")
                        .HasForeignKey("AssignedClerk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.CashRegisterEntity", "CashRegisterEntity")
                        .WithMany("CashRegisterEntitySessions")
                        .HasForeignKey("CashRegisterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashRegisterEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypesEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.GoodModelBaseTypeEntity", "GoodModelBaseTypeEntity")
                        .WithMany("GoodsTypesList")
                        .HasForeignKey("GoodBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodModelBaseTypeEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypesInstances", b =>
                {
                    b.HasOne("TasksAPI.Entities.GoodsTypesEntity", "GoodsTypes")
                        .WithMany("GoodsTypesInstances")
                        .HasForeignKey("GoodModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.LocationTypesInstances", "LocationTypesInstances")
                        .WithMany("GoodsTypesInstances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsTypes");

                    b.Navigation("LocationTypesInstances");
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypesInstances", b =>
                {
                    b.HasOne("TasksAPI.Entities.LocationTypesEntity", "LocationTypesEntity")
                        .WithMany("LocationTypesInstances")
                        .HasForeignKey("LocationTypeID")
                        .HasPrincipalKey("LocationType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationTypesEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserEntity", "UserEntity")
                        .WithOne("RefreshTokenEntity")
                        .HasForeignKey("TasksAPI.Entities.RefreshTokenEntity", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.ReportsEntitiesResults", b =>
                {
                    b.HasOne("TasksAPI.Entities.ReportsEntities", "ReportsEntities")
                        .WithMany("ReportsEntitiesResults")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportsEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.StoreCartsEntityDetails", b =>
                {
                    b.HasOne("TasksAPI.Entities.StoreCartsEntity", "StoreCartsEntity")
                        .WithMany("StoreCartsEntityDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreCartsEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntities", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserEntity", "Creator")
                        .WithMany("TasksEntities")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntitiesProcurements", b =>
                {
                    b.HasOne("TasksAPI.Entities.GoodsTypesEntity", "GoodsTypes")
                        .WithMany("TasksEntitiesProcurements")
                        .HasForeignKey("GoodTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.TasksEntities", "TasksEntities")
                        .WithMany("TasksEntitiesProcurements")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsTypes");

                    b.Navigation("TasksEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntitiesTransfer", b =>
                {
                    b.HasOne("TasksAPI.Entities.GoodsTypesInstances", "GoodsTypesInstances")
                        .WithMany()
                        .HasForeignKey("GoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.TasksEntities", "TasksEntities")
                        .WithMany("TasksEntitiesTransferList")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.LocationTypesInstances", "LocationTypesInstances")
                        .WithMany("TasksEntitiesTransfer")
                        .HasForeignKey("ToLocation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsTypesInstances");

                    b.Navigation("LocationTypesInstances");

                    b.Navigation("TasksEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserTypes", "UserTypes")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .HasPrincipalKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTypes");
                });

            modelBuilder.Entity("TasksAPI.Entities.Accounts", b =>
                {
                    b.Navigation("AccountsGoodsEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntity", b =>
                {
                    b.Navigation("CashRegisterEntitySessions");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodModelBaseTypeEntity", b =>
                {
                    b.Navigation("GoodsTypesList");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypesEntity", b =>
                {
                    b.Navigation("GoodsTypesInstances");

                    b.Navigation("TasksEntitiesProcurements");
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypesEntity", b =>
                {
                    b.Navigation("LocationTypesInstances");
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypesInstances", b =>
                {
                    b.Navigation("CashRegisterEntity");

                    b.Navigation("GoodsTypesInstances");

                    b.Navigation("TasksEntitiesTransfer");
                });

            modelBuilder.Entity("TasksAPI.Entities.ReportsEntities", b =>
                {
                    b.Navigation("ReportsEntitiesResults");
                });

            modelBuilder.Entity("TasksAPI.Entities.StoreCartsEntity", b =>
                {
                    b.Navigation("StoreCartsEntityDetails");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntities", b =>
                {
                    b.Navigation("TasksEntitiesProcurements");

                    b.Navigation("TasksEntitiesTransferList");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserEntity", b =>
                {
                    b.Navigation("CashRegisterEntitySessions");

                    b.Navigation("RefreshTokenEntity")
                        .IsRequired();

                    b.Navigation("TasksEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserTypes", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
