// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TasksAPI.DataBaseContext;

#nullable disable

namespace TasksAPI.Migrations
{
    [DbContext(typeof(DatabaseConnectContext))]
    [Migration("20260124121233_Data")]
    partial class Data
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocationTypesInstancesTasksEntitiesProcurements", b =>
                {
                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("LocationTypesInstancesId")
                        .HasColumnType("int");

                    b.HasKey("Location", "LocationTypesInstancesId");

                    b.HasIndex("LocationTypesInstancesId");

                    b.ToTable("LocationTypesInstancesTasksEntitiesProcurements");
                });

            modelBuilder.Entity("TasksAPI.Entities.Accounts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TasksAPI.Entities.AccountsGoodsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountsGoodsEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationID");

                    b.ToTable("CashRegisterEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntitySessions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedClerk")
                        .HasColumnType("int");

                    b.Property<int>("CashRegisterID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CloseHour")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<DateTime>("OpenHour")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedClerk");

                    b.HasIndex("CashRegisterID");

                    b.ToTable("CashRegisterEntitySessions");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodModelBaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GoodModelBaseType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5289),
                            Description = "Smartphone",
                            Manufacturer = "Samsung",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5290)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5449),
                            Description = "Smartphone",
                            Manufacturer = "Apple",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5450)
                        });
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GoodModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoodModelId");

                    b.ToTable("GoodsTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5573),
                            Description = "Samsung Smartphone",
                            GoodModelId = 1,
                            Name = "A53",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5574)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5774),
                            Description = "Samsung Smartphone",
                            GoodModelId = 1,
                            Name = "ZFLIP",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5775)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5777),
                            Description = "Samsung Smartphone",
                            GoodModelId = 1,
                            Name = "M14",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5777)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5778),
                            Description = "Samsung Smartphone",
                            GoodModelId = 1,
                            Name = "S21",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5779)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5780),
                            Description = "Apple Smartphone",
                            GoodModelId = 2,
                            Name = "Apple 15",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5781)
                        });
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypesInstances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodModelId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("serialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoodModelId");

                    b.HasIndex("LocationId");

                    b.ToTable("GoodsTypesInstances");
                });

            modelBuilder.Entity("TasksAPI.Entities.ItemMovementEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromLocation")
                        .HasColumnType("int");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<int>("ToLocation")
                        .HasColumnType("int");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("goodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ItemMovementEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationType")
                        .IsUnique();

                    b.ToTable("LocationEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4367),
                            Description = "Warehouse",
                            LocationType = 1,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4372)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4663),
                            Description = "STORE",
                            LocationType = 2,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4664)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4666),
                            Description = "CLIENT",
                            LocationType = 3,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4666)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4667),
                            Description = "SUPPLIER",
                            LocationType = 4,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4668)
                        });
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypesInstances", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeID");

                    b.ToTable("LocationTypesInstances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adress = "Iasi",
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4883),
                            Description = "MAIN Warehouse",
                            LocationTypeID = 1,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(4883)
                        },
                        new
                        {
                            Id = 2,
                            Adress = "Iasi",
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5101),
                            Description = "Iasi Mall",
                            LocationTypeID = 2,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5102)
                        },
                        new
                        {
                            Id = 3,
                            Adress = "Suceava",
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5104),
                            Description = "Suceava Mall",
                            LocationTypeID = 2,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5104)
                        },
                        new
                        {
                            Id = 4,
                            Adress = "Client",
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5105),
                            Description = "Goods Assigned to clients",
                            LocationTypeID = 3,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5106)
                        },
                        new
                        {
                            Id = 5,
                            Adress = "Iasi",
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5107),
                            Description = "Returned Items",
                            LocationTypeID = 1,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5108)
                        },
                        new
                        {
                            Id = 6,
                            Adress = "Iasi",
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5109),
                            Description = "Item Supplier",
                            LocationTypeID = 4,
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(5109)
                        });
                });

            modelBuilder.Entity("TasksAPI.Entities.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("RefreshTokenEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.ReportsEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportMode")
                        .HasColumnType("int");

                    b.Property<int>("ReportStatus")
                        .HasColumnType("int");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReportsEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.ReportsEntitiesResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReportID")
                        .HasColumnType("int");

                    b.Property<string>("ReportResults")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReportID");

                    b.ToTable("ReportsEntitiesResults");
                });

            modelBuilder.Entity("TasksAPI.Entities.StoreCartsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Remaining")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SessionID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("clerktId")
                        .HasColumnType("int");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<int>("storeLocation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StoreCartsEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.StoreCartsEntityDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodId")
                        .HasColumnType("int");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Notes");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("StoreCartsEntityDetails");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("int");

                    b.Property<int>("TaskType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("userID");

                    b.ToTable("TasksEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntitiesProcurements", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoodTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Location")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RemainingQuantity")
                        .HasColumnType("int");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GoodTypeID");

                    b.HasIndex("TaskID");

                    b.ToTable("TasksEntitiesProcurements");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntitiesTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromLocation")
                        .HasColumnType("int");

                    b.Property<int>("GoodID")
                        .HasColumnType("int");

                    b.Property<int>("TaskID")
                        .HasColumnType("int");

                    b.Property<int>("TaskStatus")
                        .HasColumnType("int");

                    b.Property<int>("ToLocation")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("serialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoodID");

                    b.HasIndex("TaskID");

                    b.HasIndex("ToLocation");

                    b.ToTable("TasksEntitiesTransfer");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserTypeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Client",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 607, DateTimeKind.Local).AddTicks(7706),
                            UserTypeId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(1418),
                            Description = "Clerk",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(1426),
                            UserTypeId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(1429),
                            Description = "Supervisor",
                            UpdatedDate = new DateTime(2026, 1, 24, 14, 12, 33, 612, DateTimeKind.Local).AddTicks(1429),
                            UserTypeId = 4
                        });
                });

            modelBuilder.Entity("LocationTypesInstancesTasksEntitiesProcurements", b =>
                {
                    b.HasOne("TasksAPI.Entities.TasksEntitiesProcurements", null)
                        .WithMany()
                        .HasForeignKey("Location")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.LocationTypesInstances", null)
                        .WithMany()
                        .HasForeignKey("LocationTypesInstancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TasksAPI.Entities.Accounts", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserTypes", "UserTypes")
                        .WithMany("Accounts")
                        .HasForeignKey("UserTypeId")
                        .HasPrincipalKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTypes");
                });

            modelBuilder.Entity("TasksAPI.Entities.AccountsGoodsEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.Accounts", "Accounts")
                        .WithMany("AccountsGoodsEntity")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.LocationTypesInstances", "LocationTypesInstances")
                        .WithMany("CashRegisterEntity")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationTypesInstances");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntitySessions", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserEntity", "User")
                        .WithMany("CashRegisterEntitySessions")
                        .HasForeignKey("AssignedClerk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.CashRegisterEntity", "CashRegisterEntity")
                        .WithMany("CashRegisterEntitySessions")
                        .HasForeignKey("CashRegisterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashRegisterEntity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypes", b =>
                {
                    b.HasOne("TasksAPI.Entities.GoodModelBaseType", "GoodModelBaseType")
                        .WithMany("GoodsTypesList")
                        .HasForeignKey("GoodModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodModelBaseType");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypesInstances", b =>
                {
                    b.HasOne("TasksAPI.Entities.GoodsTypes", "GoodsTypes")
                        .WithMany("GoodsTypesInstances")
                        .HasForeignKey("GoodModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.LocationTypesInstances", "LocationTypesInstances")
                        .WithMany("GoodsTypesInstances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsTypes");

                    b.Navigation("LocationTypesInstances");
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypesInstances", b =>
                {
                    b.HasOne("TasksAPI.Entities.LocationTypes", "LocationTypes")
                        .WithMany("LocationTypesInstances")
                        .HasForeignKey("LocationTypeID")
                        .HasPrincipalKey("LocationType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationTypes");
                });

            modelBuilder.Entity("TasksAPI.Entities.RefreshTokenEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserEntity", "UserEntity")
                        .WithOne("RefreshTokenEntity")
                        .HasForeignKey("TasksAPI.Entities.RefreshTokenEntity", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.ReportsEntitiesResults", b =>
                {
                    b.HasOne("TasksAPI.Entities.ReportsEntities", "ReportsEntities")
                        .WithMany("ReportsEntitiesResults")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportsEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.StoreCartsEntityDetails", b =>
                {
                    b.HasOne("TasksAPI.Entities.StoreCartsEntity", "StoreCartsEntity")
                        .WithMany("StoreCartsEntityDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreCartsEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntities", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserEntity", "User")
                        .WithMany("TasksEntities")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntitiesProcurements", b =>
                {
                    b.HasOne("TasksAPI.Entities.GoodsTypes", "GoodsTypes")
                        .WithMany("TasksEntitiesProcurements")
                        .HasForeignKey("GoodTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.TasksEntities", "TasksEntities")
                        .WithMany("TasksEntitiesProcurements")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GoodsTypes");

                    b.Navigation("TasksEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntitiesTransfer", b =>
                {
                    b.HasOne("TasksAPI.Entities.GoodsTypesInstances", "GoodsTypesInstances")
                        .WithMany()
                        .HasForeignKey("GoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.TasksEntities", "TasksEntities")
                        .WithMany("TasksEntitiesTransfer")
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TasksAPI.Entities.LocationTypesInstances", "LocationTypesInstances")
                        .WithMany("TasksEntitiesTransfer")
                        .HasForeignKey("ToLocation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsTypesInstances");

                    b.Navigation("LocationTypesInstances");

                    b.Navigation("TasksEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserEntity", b =>
                {
                    b.HasOne("TasksAPI.Entities.UserTypes", "UserTypes")
                        .WithMany("Users")
                        .HasForeignKey("UserTypeId")
                        .HasPrincipalKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserTypes");
                });

            modelBuilder.Entity("TasksAPI.Entities.Accounts", b =>
                {
                    b.Navigation("AccountsGoodsEntity");
                });

            modelBuilder.Entity("TasksAPI.Entities.CashRegisterEntity", b =>
                {
                    b.Navigation("CashRegisterEntitySessions");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodModelBaseType", b =>
                {
                    b.Navigation("GoodsTypesList");
                });

            modelBuilder.Entity("TasksAPI.Entities.GoodsTypes", b =>
                {
                    b.Navigation("GoodsTypesInstances");

                    b.Navigation("TasksEntitiesProcurements");
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypes", b =>
                {
                    b.Navigation("LocationTypesInstances");
                });

            modelBuilder.Entity("TasksAPI.Entities.LocationTypesInstances", b =>
                {
                    b.Navigation("CashRegisterEntity");

                    b.Navigation("GoodsTypesInstances");

                    b.Navigation("TasksEntitiesTransfer");
                });

            modelBuilder.Entity("TasksAPI.Entities.ReportsEntities", b =>
                {
                    b.Navigation("ReportsEntitiesResults");
                });

            modelBuilder.Entity("TasksAPI.Entities.StoreCartsEntity", b =>
                {
                    b.Navigation("StoreCartsEntityDetails");
                });

            modelBuilder.Entity("TasksAPI.Entities.TasksEntities", b =>
                {
                    b.Navigation("TasksEntitiesProcurements");

                    b.Navigation("TasksEntitiesTransfer");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserEntity", b =>
                {
                    b.Navigation("CashRegisterEntitySessions");

                    b.Navigation("RefreshTokenEntity")
                        .IsRequired();

                    b.Navigation("TasksEntities");
                });

            modelBuilder.Entity("TasksAPI.Entities.UserTypes", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
